### ISSUE TITLE
There is no thanks for Tao

### ISSUE THREAD

**Issue by Rouxles** [GuidoDipietro/julia-small-rubiks-cube-model#1]
I believe it is quite important to thank Tao for the Biang Biang Noodles.

**Comment by GuidoDipietro** [comment]
Oh, can't believe I forgot about that! I will perform an addition to my README.md file ASAP to try-catch and solve this issue.

**Comment by GuidoDipietro** [comment]
The pobler is gone.

**Comment by Rouxles** [comment]
@GuidoDipietro
